name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: windows-latest
    env:
      CI: false
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install windows build tools
        run: npm i -g windows-build-tools@4.0.0
      - name: install node-gyp
        run: npm i -g node-gyp@latest
      - name: update path variables
        run: set 'path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Bin'
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
