name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: linux
    env:
      CI: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
