name: test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    env:
      CI: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # - name: clean npm cache
      #   run: npm cache clean -f
      # - name: install dependencies
      #   run: npm ci
      # - name: build
      #   run: npm run build
      # - name: tests
      #   run: npm run test
      - name: preloads
        run: echo "PRELOAD_SHASUM_ORIGIN=$(shasum packages/app/src/preloadApi.ts)" >> $GITHUB_ENV
      - name: preloads
        run: echo "PRELOAD_SHASUM_NEW=asdf" >> $GITHUB_ENV
      - name: test value
        run: |
          test $PRELOAD_SHASUM_ORIGIN = $PRELOAD_SHASUM_NEW
