name: test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    env:
      CI: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node-gyp
        run: npm i -g node-gyp@latest
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: install dmg-license
        run: npm i dmg-license
      - name: tests
        run: npm run test
